export { default as Navbar } from './navbar'
export { default as Home } from './Home'
export { default as SingleProduct } from './SingleProduct'
export { default as Cart } from './Cart'
export { default as Signup } from './Signup'
export { default as Login } from './LogIn'
export { default as Reviews } from './Reviews'
export { default as ReviewItem } from './ReviewItem'
//export {default as Signup} from './Signup'
//export {default as Login} from './Login'
export { default as UserProfile } from './UserProfile'
export { default as EditUser } from './EditUser'
